export type Command = {
  name: string;
  description: string;
  syntax: string;
  examples: { cmd: string; desc: string }[];
  options: { flag: string; desc: string }[];
  category: string;
};

export type CategoryDef = {
  id: string;
  label: string;
  icon: string;
};

export const categories: CategoryDef[] = [
  { id: "all", label: "Toutes", icon: "Terminal" },
  { id: "files", label: "Fichiers", icon: "FolderOpen" },
  { id: "text", label: "Texte", icon: "FileText" },
  { id: "network", label: "Réseau", icon: "Globe" },
  { id: "process", label: "Processus", icon: "Cpu" },
  { id: "disk", label: "Disque", icon: "HardDrive" },
  { id: "permissions", label: "Permissions", icon: "Users" },
  { id: "system", label: "Système", icon: "Settings" },
  { id: "transfer", label: "Transfert", icon: "ArrowLeftRight" },
  { id: "archives", label: "Archives", icon: "Archive" },
];

export const pipeCombinations = [
  { cmd: "ps aux | grep node | awk '{print $2}' | xargs kill", desc: "Trouver et tuer tous les processus Node.js" },
  { cmd: "find . -name '*.log' -mtime +30 | xargs rm -f", desc: "Supprimer les fichiers .log de plus de 30 jours" },
  { cmd: "cat access.log | awk '{print $1}' | sort | uniq -c | sort -rn | head -10", desc: "Top 10 des IPs dans un access log" },
  { cmd: "du -sh * | sort -rh | head -5", desc: "Les 5 plus gros dossiers/fichiers" },
  { cmd: "grep -rl 'TODO' src/ | xargs sed -i 's/TODO/DONE/g'", desc: "Remplacer TODO par DONE dans tout le projet" },
  { cmd: "curl -s https://api.example.com | jq '.data[] | .name'", desc: "Extraire les noms depuis une API JSON" },
  { cmd: "history | awk '{print $2}' | sort | uniq -c | sort -rn | head -10", desc: "Top 10 des commandes les plus utilisées" },
  { cmd: "find . -type f -name '*.ts' | xargs wc -l | sort -rn | head", desc: "Fichiers TypeScript les plus longs" },
  { cmd: "docker ps -q | xargs docker stop", desc: "Arrêter tous les conteneurs Docker en cours" },
  { cmd: "ls -la | awk '{print $5, $9}' | sort -rn | head", desc: "Fichiers triés par taille dans le dossier courant" },
];

export const commands: Command[] = [
  // === FILES ===
  { name: "ls", description: "Lister les fichiers et répertoires", syntax: "ls [options] [path]", category: "files",
    options: [{ flag: "-l", desc: "Format long" }, { flag: "-a", desc: "Fichiers cachés" }, { flag: "-h", desc: "Tailles lisibles" }, { flag: "-R", desc: "Récursif" }, { flag: "-S", desc: "Trier par taille" }, { flag: "-t", desc: "Trier par date" }],
    examples: [{ cmd: "ls -lah", desc: "Liste détaillée avec tailles lisibles" }, { cmd: "ls -R /var/log", desc: "Liste récursive des logs" }, { cmd: "ls -lt --color=auto", desc: "Liste triée par date avec couleurs" }] },
  { name: "cd", description: "Changer de répertoire", syntax: "cd [directory]", category: "files",
    options: [{ flag: "~", desc: "Répertoire home" }, { flag: "-", desc: "Répertoire précédent" }, { flag: "..", desc: "Parent" }],
    examples: [{ cmd: "cd ~/projects", desc: "Aller dans le dossier projects" }, { cmd: "cd -", desc: "Revenir au répertoire précédent" }] },
  { name: "cp", description: "Copier des fichiers ou répertoires", syntax: "cp [options] source dest", category: "files",
    options: [{ flag: "-r", desc: "Récursif (dossiers)" }, { flag: "-i", desc: "Confirmation avant écrasement" }, { flag: "-v", desc: "Verbose" }, { flag: "-p", desc: "Préserver les attributs" }],
    examples: [{ cmd: "cp -r src/ backup/", desc: "Copier un dossier" }, { cmd: "cp file.txt /tmp/", desc: "Copier un fichier" }] },
  { name: "mv", description: "Déplacer ou renommer", syntax: "mv [options] source dest", category: "files",
    options: [{ flag: "-i", desc: "Confirmation" }, { flag: "-v", desc: "Verbose" }, { flag: "-n", desc: "Ne pas écraser" }],
    examples: [{ cmd: "mv old.txt new.txt", desc: "Renommer un fichier" }, { cmd: "mv *.log /archive/", desc: "Déplacer les logs" }] },
  { name: "rm", description: "Supprimer des fichiers ou répertoires", syntax: "rm [options] file", category: "files",
    options: [{ flag: "-r", desc: "Récursif" }, { flag: "-f", desc: "Forcer sans confirmation" }, { flag: "-i", desc: "Demander confirmation" }],
    examples: [{ cmd: "rm -rf node_modules/", desc: "Supprimer un dossier" }, { cmd: "rm *.tmp", desc: "Supprimer les fichiers .tmp" }] },
  { name: "find", description: "Rechercher des fichiers", syntax: "find [path] [expression]", category: "files",
    options: [{ flag: "-name", desc: "Par nom" }, { flag: "-type f", desc: "Fichiers uniquement" }, { flag: "-mtime", desc: "Par date de modification" }, { flag: "-size", desc: "Par taille" }, { flag: "-exec", desc: "Exécuter une commande" }],
    examples: [{ cmd: "find . -name '*.js' -type f", desc: "Trouver les fichiers JS" }, { cmd: "find /var -size +100M", desc: "Fichiers > 100Mo" }, { cmd: "find . -mtime -7 -name '*.log'", desc: "Logs modifiés < 7 jours" }] },
  { name: "mkdir", description: "Créer un répertoire", syntax: "mkdir [options] directory", category: "files",
    options: [{ flag: "-p", desc: "Créer les parents si nécessaire" }, { flag: "-m", desc: "Définir les permissions" }],
    examples: [{ cmd: "mkdir -p src/components/ui", desc: "Créer une arborescence complète" }, { cmd: "mkdir -m 755 /opt/app", desc: "Créer avec permissions" }] },
  { name: "touch", description: "Créer un fichier vide ou mettre à jour la date", syntax: "touch [options] file", category: "files",
    options: [{ flag: "-a", desc: "Modifier la date d'accès" }, { flag: "-m", desc: "Modifier la date de modification" }],
    examples: [{ cmd: "touch newfile.txt", desc: "Créer un fichier vide" }, { cmd: "touch -t 202301010000 file.txt", desc: "Définir une date spécifique" }] },
  { name: "ln", description: "Créer des liens (symboliques ou physiques)", syntax: "ln [options] target link_name", category: "files",
    options: [{ flag: "-s", desc: "Lien symbolique" }, { flag: "-f", desc: "Forcer la création" }],
    examples: [{ cmd: "ln -s /usr/bin/python3 /usr/bin/python", desc: "Lien symbolique" }, { cmd: "ln -sf target.txt link.txt", desc: "Forcer un lien symbolique" }] },
  { name: "stat", description: "Afficher les métadonnées d'un fichier", syntax: "stat [options] file", category: "files",
    options: [{ flag: "-c", desc: "Format personnalisé" }],
    examples: [{ cmd: "stat package.json", desc: "Infos complètes d'un fichier" }, { cmd: "stat -c '%s %n' *.ts", desc: "Taille et nom des fichiers TS" }] },
  { name: "tree", description: "Afficher l'arborescence de fichiers", syntax: "tree [options] [path]", category: "files",
    options: [{ flag: "-L", desc: "Profondeur max" }, { flag: "-d", desc: "Dossiers uniquement" }, { flag: "-I", desc: "Exclure un pattern" }],
    examples: [{ cmd: "tree -L 2 -I node_modules", desc: "Arborescence profondeur 2 sans node_modules" }, { cmd: "tree -d src/", desc: "Dossiers uniquement" }] },

  // === TEXT ===
  { name: "grep", description: "Rechercher dans le contenu des fichiers", syntax: "grep [options] pattern [file]", category: "text",
    options: [{ flag: "-r", desc: "Récursif" }, { flag: "-i", desc: "Ignorer la casse" }, { flag: "-n", desc: "Numéro de ligne" }, { flag: "-c", desc: "Compter les occurrences" }, { flag: "-v", desc: "Inverser (lignes ne correspondant pas)" }, { flag: "-E", desc: "Regex étendue (egrep)" }],
    examples: [{ cmd: "grep -rn 'TODO' src/", desc: "Trouver les TODO dans le code" }, { cmd: "grep -i 'error' /var/log/syslog", desc: "Chercher les erreurs" }, { cmd: "grep -E '^[0-9]+' file.txt", desc: "Lignes commençant par un nombre" }] },
  { name: "cat", description: "Afficher le contenu d'un fichier", syntax: "cat [options] [file]", category: "text",
    options: [{ flag: "-n", desc: "Numéroter les lignes" }, { flag: "-b", desc: "Numéroter les lignes non vides" }],
    examples: [{ cmd: "cat -n config.yml", desc: "Afficher avec numéros de lignes" }, { cmd: "cat file1 file2 > merged", desc: "Concaténer des fichiers" }] },
  { name: "sed", description: "Éditeur de flux (stream editor)", syntax: "sed [options] 'script' [file]", category: "text",
    options: [{ flag: "-i", desc: "Modifier en place" }, { flag: "-e", desc: "Expression" }, { flag: "-n", desc: "Supprimer la sortie par défaut" }],
    examples: [{ cmd: "sed -i 's/old/new/g' file.txt", desc: "Remplacer globalement" }, { cmd: "sed -n '5,10p' file.txt", desc: "Afficher les lignes 5-10" }] },
  { name: "awk", description: "Traitement de texte avancé", syntax: "awk 'pattern { action }' [file]", category: "text",
    options: [{ flag: "-F", desc: "Séparateur de champ" }, { flag: "NR", desc: "Numéro de ligne" }, { flag: "$N", desc: "N-ième champ" }],
    examples: [{ cmd: "awk -F: '{print $1}' /etc/passwd", desc: "Extraire les noms d'utilisateurs" }, { cmd: "awk '{sum+=$1} END {print sum}'", desc: "Somme d'une colonne" }] },
  { name: "head", description: "Afficher le début d'un fichier", syntax: "head [options] [file]", category: "text",
    options: [{ flag: "-n", desc: "Nombre de lignes" }, { flag: "-c", desc: "Nombre d'octets" }],
    examples: [{ cmd: "head -n 20 file.txt", desc: "Les 20 premières lignes" }, { cmd: "head -c 1024 binary.dat", desc: "Les 1024 premiers octets" }] },
  { name: "tail", description: "Afficher la fin d'un fichier", syntax: "tail [options] [file]", category: "text",
    options: [{ flag: "-n", desc: "Nombre de lignes" }, { flag: "-f", desc: "Suivre en temps réel" }, { flag: "-F", desc: "Suivre même après rotation" }],
    examples: [{ cmd: "tail -f /var/log/syslog", desc: "Suivre les logs en temps réel" }, { cmd: "tail -n 50 error.log", desc: "Les 50 dernières lignes" }] },
  { name: "sort", description: "Trier les lignes d'un fichier", syntax: "sort [options] [file]", category: "text",
    options: [{ flag: "-r", desc: "Tri inversé" }, { flag: "-n", desc: "Tri numérique" }, { flag: "-u", desc: "Supprimer les doublons" }, { flag: "-k", desc: "Trier par colonne" }, { flag: "-h", desc: "Tailles lisibles (1K, 2M)" }],
    examples: [{ cmd: "sort -rn scores.txt", desc: "Tri numérique décroissant" }, { cmd: "sort -t, -k2 data.csv", desc: "Trier un CSV par 2e colonne" }] },
  { name: "uniq", description: "Filtrer les lignes dupliquées (triées)", syntax: "uniq [options] [file]", category: "text",
    options: [{ flag: "-c", desc: "Compter les occurrences" }, { flag: "-d", desc: "N'afficher que les doublons" }, { flag: "-u", desc: "N'afficher que les uniques" }],
    examples: [{ cmd: "sort file.txt | uniq -c | sort -rn", desc: "Fréquence des lignes" }, { cmd: "sort names.txt | uniq -d", desc: "N'afficher que les doublons" }] },
  { name: "wc", description: "Compter lignes, mots, caractères", syntax: "wc [options] [file]", category: "text",
    options: [{ flag: "-l", desc: "Nombre de lignes" }, { flag: "-w", desc: "Nombre de mots" }, { flag: "-c", desc: "Nombre d'octets" }],
    examples: [{ cmd: "wc -l *.ts", desc: "Compter les lignes de chaque fichier TS" }, { cmd: "find . -name '*.tsx' | xargs wc -l", desc: "Total des lignes TSX" }] },
  { name: "cut", description: "Extraire des colonnes/champs", syntax: "cut [options] [file]", category: "text",
    options: [{ flag: "-d", desc: "Délimiteur" }, { flag: "-f", desc: "Champs (colonnes)" }, { flag: "-c", desc: "Caractères" }],
    examples: [{ cmd: "cut -d: -f1,3 /etc/passwd", desc: "Extraire user et UID" }, { cmd: "cut -c1-10 file.txt", desc: "Les 10 premiers caractères par ligne" }] },
  { name: "tr", description: "Traduire ou supprimer des caractères", syntax: "tr [options] SET1 [SET2]", category: "text",
    options: [{ flag: "-d", desc: "Supprimer les caractères" }, { flag: "-s", desc: "Compresser les répétitions" }],
    examples: [{ cmd: "echo 'hello' | tr 'a-z' 'A-Z'", desc: "Convertir en majuscules" }, { cmd: "cat file.txt | tr -d '\\r'", desc: "Supprimer les retours chariot Windows" }] },
  { name: "diff", description: "Comparer deux fichiers", syntax: "diff [options] file1 file2", category: "text",
    options: [{ flag: "-u", desc: "Format unifié" }, { flag: "-r", desc: "Récursif (dossiers)" }, { flag: "--color", desc: "Sortie colorée" }],
    examples: [{ cmd: "diff -u old.txt new.txt", desc: "Diff au format patch" }, { cmd: "diff -r dir1/ dir2/", desc: "Comparer deux dossiers" }] },
  { name: "tee", description: "Lire stdin et écrire dans stdout ET un fichier", syntax: "tee [options] file", category: "text",
    options: [{ flag: "-a", desc: "Ajouter au fichier (append)" }],
    examples: [{ cmd: "echo 'log entry' | tee -a app.log", desc: "Logger et afficher" }, { cmd: "make 2>&1 | tee build.log", desc: "Capturer la sortie de build" }] },
  { name: "xargs", description: "Construire des commandes depuis stdin", syntax: "xargs [options] [command]", category: "text",
    options: [{ flag: "-I {}", desc: "Placeholder de remplacement" }, { flag: "-n", desc: "Max arguments par commande" }, { flag: "-P", desc: "Parallélisme" }],
    examples: [{ cmd: "find . -name '*.tmp' | xargs rm", desc: "Supprimer les fichiers trouvés" }, { cmd: "cat urls.txt | xargs -P 4 -I {} curl {}", desc: "Télécharger 4 URLs en parallèle" }] },

  // === NETWORK ===
  { name: "curl", description: "Transférer des données via URL", syntax: "curl [options] [URL]", category: "network",
    options: [{ flag: "-X", desc: "Méthode HTTP" }, { flag: "-H", desc: "Header" }, { flag: "-d", desc: "Données POST" }, { flag: "-o", desc: "Fichier de sortie" }, { flag: "-s", desc: "Silencieux" }, { flag: "-k", desc: "Ignorer SSL" }],
    examples: [{ cmd: "curl -X POST -H 'Content-Type: application/json' -d '{\"key\":\"val\"}' https://api.example.com", desc: "POST JSON" }, { cmd: "curl -sO https://example.com/file.zip", desc: "Télécharger un fichier" }] },
  { name: "ssh", description: "Connexion sécurisée à un serveur distant", syntax: "ssh [options] user@host", category: "network",
    options: [{ flag: "-p", desc: "Port" }, { flag: "-i", desc: "Clé privée" }, { flag: "-L", desc: "Tunnel local" }, { flag: "-v", desc: "Verbose" }],
    examples: [{ cmd: "ssh -i ~/.ssh/key.pem user@server.com", desc: "Connexion avec clé" }, { cmd: "ssh -L 8080:localhost:3000 user@server", desc: "Tunnel SSH" }] },
  { name: "wget", description: "Télécharger des fichiers depuis le web", syntax: "wget [options] URL", category: "network",
    options: [{ flag: "-O", desc: "Fichier de sortie" }, { flag: "-q", desc: "Mode silencieux" }, { flag: "-r", desc: "Récursif" }, { flag: "-c", desc: "Reprendre un téléchargement" }],
    examples: [{ cmd: "wget -O latest.tar.gz https://example.com/file.tar.gz", desc: "Télécharger et renommer" }, { cmd: "wget -c https://example.com/big-file.iso", desc: "Reprendre un téléchargement interrompu" }] },
  { name: "ping", description: "Tester la connectivité réseau", syntax: "ping [options] host", category: "network",
    options: [{ flag: "-c", desc: "Nombre de paquets" }, { flag: "-i", desc: "Intervalle (secondes)" }, { flag: "-W", desc: "Timeout" }],
    examples: [{ cmd: "ping -c 4 google.com", desc: "4 pings vers Google" }, { cmd: "ping -c 1 -W 2 192.168.1.1", desc: "Test rapide avec timeout" }] },
  { name: "netstat", description: "Statistiques réseau et connexions", syntax: "netstat [options]", category: "network",
    options: [{ flag: "-tulpn", desc: "TCP/UDP listening avec PID" }, { flag: "-a", desc: "Toutes les connexions" }, { flag: "-r", desc: "Table de routage" }],
    examples: [{ cmd: "netstat -tulpn", desc: "Ports en écoute avec processus" }, { cmd: "netstat -an | grep ESTABLISHED", desc: "Connexions actives" }] },
  { name: "ss", description: "Socket statistics (remplaçant netstat)", syntax: "ss [options]", category: "network",
    options: [{ flag: "-t", desc: "TCP" }, { flag: "-l", desc: "Listening" }, { flag: "-p", desc: "Processus" }, { flag: "-n", desc: "Numérique" }],
    examples: [{ cmd: "ss -tlnp", desc: "Ports TCP en écoute" }, { cmd: "ss -s", desc: "Résumé des statistiques" }] },
  { name: "ip", description: "Gestion des interfaces réseau", syntax: "ip [object] [command]", category: "network",
    options: [{ flag: "addr", desc: "Adresses IP" }, { flag: "route", desc: "Table de routage" }, { flag: "link", desc: "Interfaces" }],
    examples: [{ cmd: "ip addr show", desc: "Afficher les adresses IP" }, { cmd: "ip route show", desc: "Table de routage" }] },
  { name: "nslookup", description: "Résolution DNS", syntax: "nslookup [options] host", category: "network",
    options: [{ flag: "-type=MX", desc: "Enregistrements MX" }, { flag: "-type=A", desc: "Enregistrements A" }],
    examples: [{ cmd: "nslookup google.com", desc: "Résoudre un domaine" }, { cmd: "nslookup -type=MX example.com", desc: "Serveurs mail" }] },

  // === PROCESS ===
  { name: "ps", description: "Lister les processus", syntax: "ps [options]", category: "process",
    options: [{ flag: "aux", desc: "Tous les processus détaillés" }, { flag: "-ef", desc: "Format complet" }, { flag: "--sort", desc: "Trier" }],
    examples: [{ cmd: "ps aux | grep node", desc: "Trouver les processus Node" }, { cmd: "ps aux --sort=-%mem | head", desc: "Top processus par mémoire" }] },
  { name: "kill", description: "Terminer un processus", syntax: "kill [signal] PID", category: "process",
    options: [{ flag: "-9", desc: "SIGKILL (forcer)" }, { flag: "-15", desc: "SIGTERM (gracieux)" }, { flag: "-l", desc: "Lister les signaux" }],
    examples: [{ cmd: "kill -9 12345", desc: "Forcer l'arrêt" }, { cmd: "killall node", desc: "Tuer tous les processus node" }] },
  { name: "top", description: "Moniteur système en temps réel", syntax: "top [options]", category: "process",
    options: [{ flag: "-o %CPU", desc: "Trier par CPU" }, { flag: "-o %MEM", desc: "Trier par mémoire" }, { flag: "-n 1", desc: "Une seule itération" }],
    examples: [{ cmd: "top -o %MEM", desc: "Trier par utilisation mémoire" }, { cmd: "htop", desc: "Version améliorée (si installé)" }] },
  { name: "lsof", description: "Lister les fichiers ouverts", syntax: "lsof [options]", category: "process",
    options: [{ flag: "-i", desc: "Connexions réseau" }, { flag: "-p", desc: "Par PID" }, { flag: "-u", desc: "Par utilisateur" }],
    examples: [{ cmd: "lsof -i :3000", desc: "Processus utilisant le port 3000" }, { cmd: "lsof -u www-data", desc: "Fichiers ouverts par www-data" }] },
  { name: "nohup", description: "Exécuter un processus détaché du terminal", syntax: "nohup command &", category: "process",
    options: [],
    examples: [{ cmd: "nohup node server.js &", desc: "Lancer un serveur en arrière-plan" }, { cmd: "nohup ./script.sh > output.log 2>&1 &", desc: "Avec redirection des logs" }] },
  { name: "crontab", description: "Planifier des tâches récurrentes", syntax: "crontab [options]", category: "process",
    options: [{ flag: "-e", desc: "Éditer la crontab" }, { flag: "-l", desc: "Lister les tâches" }, { flag: "-r", desc: "Supprimer la crontab" }],
    examples: [{ cmd: "crontab -e", desc: "Éditer les tâches planifiées" }, { cmd: "0 2 * * * /opt/backup.sh", desc: "Backup quotidien à 2h du matin" }] },

  // === DISK ===
  { name: "df", description: "Espace disque des systèmes de fichiers", syntax: "df [options]", category: "disk",
    options: [{ flag: "-h", desc: "Tailles lisibles" }, { flag: "-T", desc: "Type de filesystem" }, { flag: "-i", desc: "Inodes" }],
    examples: [{ cmd: "df -hT", desc: "Espace disque avec types" }, { cmd: "df -h /dev/sda1", desc: "Espace d'une partition" }] },
  { name: "du", description: "Taille des fichiers et dossiers", syntax: "du [options] [path]", category: "disk",
    options: [{ flag: "-h", desc: "Tailles lisibles" }, { flag: "-s", desc: "Total uniquement" }, { flag: "--max-depth", desc: "Profondeur max" }],
    examples: [{ cmd: "du -sh *", desc: "Taille de chaque dossier" }, { cmd: "du -h --max-depth=1 | sort -rh", desc: "Trier par taille" }] },
  { name: "mount", description: "Monter un système de fichiers", syntax: "mount [options] device dir", category: "disk",
    options: [{ flag: "-t", desc: "Type de filesystem" }, { flag: "-o", desc: "Options de montage" }],
    examples: [{ cmd: "mount /dev/sdb1 /mnt/usb", desc: "Monter une clé USB" }, { cmd: "mount -o loop image.iso /mnt/iso", desc: "Monter un ISO" }] },
  { name: "fdisk", description: "Gestion des partitions disque", syntax: "fdisk [options] device", category: "disk",
    options: [{ flag: "-l", desc: "Lister les partitions" }],
    examples: [{ cmd: "fdisk -l", desc: "Lister toutes les partitions" }, { cmd: "fdisk /dev/sda", desc: "Gérer les partitions de sda" }] },

  // === PERMISSIONS ===
  { name: "chmod", description: "Modifier les permissions", syntax: "chmod [options] mode file", category: "permissions",
    options: [{ flag: "-R", desc: "Récursif" }, { flag: "u+x", desc: "Exécutable pour le propriétaire" }, { flag: "755", desc: "rwxr-xr-x" }],
    examples: [{ cmd: "chmod +x script.sh", desc: "Rendre exécutable" }, { cmd: "chmod -R 644 *.html", desc: "Permissions sur les fichiers HTML" }] },
  { name: "chown", description: "Modifier le propriétaire", syntax: "chown [options] user:group file", category: "permissions",
    options: [{ flag: "-R", desc: "Récursif" }],
    examples: [{ cmd: "chown -R www-data:www-data /var/www", desc: "Changer le propriétaire web" }, { cmd: "chown user:group file.txt", desc: "Changer propriétaire et groupe" }] },
  { name: "umask", description: "Définir les permissions par défaut", syntax: "umask [mode]", category: "permissions",
    options: [],
    examples: [{ cmd: "umask 022", desc: "Fichiers 644, dossiers 755 par défaut" }, { cmd: "umask -S", desc: "Afficher en format symbolique" }] },

  // === SYSTEM ===
  { name: "systemctl", description: "Gérer les services systemd", syntax: "systemctl [command] [unit]", category: "system",
    options: [{ flag: "start", desc: "Démarrer un service" }, { flag: "stop", desc: "Arrêter un service" }, { flag: "restart", desc: "Redémarrer" }, { flag: "enable", desc: "Activer au démarrage" }, { flag: "status", desc: "État d'un service" }],
    examples: [{ cmd: "systemctl status nginx", desc: "État du service nginx" }, { cmd: "systemctl restart postgresql", desc: "Redémarrer PostgreSQL" }, { cmd: "systemctl enable --now docker", desc: "Activer et démarrer Docker" }] },
  { name: "journalctl", description: "Consulter les logs systemd", syntax: "journalctl [options]", category: "system",
    options: [{ flag: "-u", desc: "Par service" }, { flag: "-f", desc: "Suivre en temps réel" }, { flag: "--since", desc: "Depuis une date" }, { flag: "-n", desc: "Dernières N lignes" }],
    examples: [{ cmd: "journalctl -u nginx -f", desc: "Suivre les logs nginx" }, { cmd: "journalctl --since '1 hour ago'", desc: "Logs de la dernière heure" }] },
  { name: "uname", description: "Informations système", syntax: "uname [options]", category: "system",
    options: [{ flag: "-a", desc: "Toutes les infos" }, { flag: "-r", desc: "Version du noyau" }, { flag: "-m", desc: "Architecture" }],
    examples: [{ cmd: "uname -a", desc: "Toutes les informations système" }, { cmd: "uname -r", desc: "Version du noyau Linux" }] },
  { name: "hostname", description: "Nom de la machine", syntax: "hostname [options]", category: "system",
    options: [{ flag: "-I", desc: "Toutes les adresses IP" }, { flag: "-f", desc: "FQDN" }],
    examples: [{ cmd: "hostname -I", desc: "Adresses IP de la machine" }, { cmd: "hostnamectl set-hostname myserver", desc: "Changer le nom de la machine" }] },
  { name: "uptime", description: "Durée depuis le dernier démarrage", syntax: "uptime", category: "system",
    options: [{ flag: "-p", desc: "Format lisible" }],
    examples: [{ cmd: "uptime -p", desc: "Uptime en format lisible" }] },
  { name: "free", description: "Utilisation de la mémoire", syntax: "free [options]", category: "system",
    options: [{ flag: "-h", desc: "Tailles lisibles" }, { flag: "-m", desc: "En mégaoctets" }, { flag: "-s", desc: "Rafraîchir toutes les N secondes" }],
    examples: [{ cmd: "free -h", desc: "Mémoire en format lisible" }, { cmd: "free -h -s 2", desc: "Rafraîchir toutes les 2s" }] },
  { name: "env", description: "Afficher/modifier les variables d'environnement", syntax: "env [options] [command]", category: "system",
    options: [{ flag: "-i", desc: "Environnement vide" }],
    examples: [{ cmd: "env | grep PATH", desc: "Voir le PATH" }, { cmd: "export NODE_ENV=production", desc: "Définir une variable" }] },
  { name: "alias", description: "Créer des raccourcis de commande", syntax: "alias name='command'", category: "system",
    options: [],
    examples: [{ cmd: "alias ll='ls -lah'", desc: "Raccourci pour ls détaillé" }, { cmd: "alias gs='git status'", desc: "Raccourci git status" }] },
  { name: "which", description: "Localiser un exécutable", syntax: "which [command]", category: "system",
    options: [],
    examples: [{ cmd: "which node", desc: "Chemin de l'exécutable Node" }, { cmd: "which python3", desc: "Chemin de Python 3" }] },
  { name: "date", description: "Afficher ou modifier la date/heure", syntax: "date [options]", category: "system",
    options: [{ flag: "+%Y-%m-%d", desc: "Format personnalisé" }, { flag: "-u", desc: "UTC" }],
    examples: [{ cmd: "date '+%Y-%m-%d %H:%M:%S'", desc: "Date formatée" }, { cmd: "date -u", desc: "Date en UTC" }] },

  // === TRANSFER ===
  { name: "scp", description: "Copier des fichiers via SSH", syntax: "scp [options] source dest", category: "transfer",
    options: [{ flag: "-r", desc: "Récursif" }, { flag: "-P", desc: "Port SSH" }, { flag: "-i", desc: "Clé privée" }, { flag: "-C", desc: "Compression" }],
    examples: [{ cmd: "scp file.txt user@server:/home/user/", desc: "Envoyer un fichier" }, { cmd: "scp -r user@server:/var/log/ ./logs/", desc: "Récupérer un dossier" }] },
  { name: "rsync", description: "Synchronisation efficace de fichiers", syntax: "rsync [options] source dest", category: "transfer",
    options: [{ flag: "-a", desc: "Mode archive (récursif + permissions)" }, { flag: "-v", desc: "Verbose" }, { flag: "-z", desc: "Compression" }, { flag: "--delete", desc: "Supprimer les fichiers absents de la source" }, { flag: "--dry-run", desc: "Simulation sans modification" }],
    examples: [{ cmd: "rsync -avz src/ user@server:/dest/", desc: "Sync avec compression" }, { cmd: "rsync -avz --delete /backup/ /mnt/external/", desc: "Miroir exact" }, { cmd: "rsync -avzn src/ dest/", desc: "Dry run (simulation)" }] },
  { name: "sftp", description: "Transfert de fichiers sécurisé (FTP sur SSH)", syntax: "sftp [options] user@host", category: "transfer",
    options: [{ flag: "-P", desc: "Port" }, { flag: "-i", desc: "Clé privée" }],
    examples: [{ cmd: "sftp user@server", desc: "Connexion SFTP" }, { cmd: "sftp> put localfile.txt", desc: "Envoyer un fichier (dans la session)" }] },

  // === ARCHIVES ===
  { name: "tar", description: "Archivage et compression", syntax: "tar [options] [archive] [files]", category: "archives",
    options: [{ flag: "-c", desc: "Créer" }, { flag: "-x", desc: "Extraire" }, { flag: "-z", desc: "gzip" }, { flag: "-j", desc: "bzip2" }, { flag: "-v", desc: "Verbose" }, { flag: "-f", desc: "Fichier" }, { flag: "-t", desc: "Lister le contenu" }],
    examples: [{ cmd: "tar -czf archive.tar.gz dossier/", desc: "Créer une archive gzip" }, { cmd: "tar -xzf archive.tar.gz", desc: "Extraire une archive gzip" }, { cmd: "tar -tf archive.tar.gz", desc: "Lister le contenu sans extraire" }] },
  { name: "zip", description: "Créer des archives ZIP", syntax: "zip [options] archive.zip files", category: "archives",
    options: [{ flag: "-r", desc: "Récursif" }, { flag: "-e", desc: "Chiffrer (mot de passe)" }, { flag: "-9", desc: "Compression maximale" }],
    examples: [{ cmd: "zip -r project.zip src/", desc: "Zipper un dossier" }, { cmd: "zip -e secret.zip confidential.pdf", desc: "Zip avec mot de passe" }] },
  { name: "unzip", description: "Extraire des archives ZIP", syntax: "unzip [options] archive.zip", category: "archives",
    options: [{ flag: "-d", desc: "Répertoire de destination" }, { flag: "-l", desc: "Lister le contenu" }, { flag: "-o", desc: "Écraser sans confirmation" }],
    examples: [{ cmd: "unzip archive.zip -d /opt/", desc: "Extraire dans un dossier" }, { cmd: "unzip -l archive.zip", desc: "Lister le contenu" }] },
  { name: "gzip", description: "Compresser / décompresser un fichier", syntax: "gzip [options] file", category: "archives",
    options: [{ flag: "-d", desc: "Décompresser" }, { flag: "-k", desc: "Garder le fichier original" }, { flag: "-9", desc: "Compression maximale" }],
    examples: [{ cmd: "gzip -k large-file.log", desc: "Compresser en gardant l'original" }, { cmd: "gzip -d file.gz", desc: "Décompresser" }] },
];
