// Centralized tool registry — single source of truth for all tools
export interface ToolEntry {
  title: string;
  url: string;
  category: string;
  description?: string;
  shortDesc?: string;
  features?: string[];
  guide?: string[];
}

export interface ToolCategory {
  label: string;
  tools: ToolEntry[];
}

interface RawItem {
  title: string;
  url: string;
  desc?: string;
  shortDesc?: string;
  features?: string[];
  guide?: string[];
}

const raw: { label: string; items: RawItem[] }[] = [
  {
    label: "Texte & Formats",
    items: [
      { title: "Markdown", url: "/markdown", desc: "Éditeur avec preview temps réel",
        shortDesc: "Éditeur Markdown complet avec prévisualisation en temps réel, support GFM et export HTML.",
        features: ["Édition avec preview côte à côte", "Support GitHub Flavored Markdown", "Export HTML", "Coloration syntaxique des blocs de code", "Compteur de mots intégré"],
        guide: ["Saisissez votre Markdown dans le panneau de gauche", "La prévisualisation s'affiche en temps réel à droite", "Utilisez la barre d'outils pour insérer des éléments (titres, liens, images)", "Copiez le HTML généré ou exportez votre document"] },
      { title: "Comparateur", url: "/diff", desc: "Diff entre deux textes",
        shortDesc: "Comparez deux textes côte à côte avec mise en évidence des différences ligne par ligne.",
        features: ["Comparaison côte à côte", "Surlignage des ajouts/suppressions", "Mode unified ou split", "Numéros de lignes"],
        guide: ["Collez le premier texte dans le panneau de gauche", "Collez le second texte dans le panneau de droite", "Les différences sont surlignées automatiquement", "Basculez entre les modes d'affichage selon vos besoins"] },
      { title: "Analyseur", url: "/text-analyzer", desc: "Stats et métriques",
        shortDesc: "Analysez votre texte : comptage de mots, caractères, phrases, temps de lecture et statistiques avancées.",
        features: ["Comptage mots/caractères/phrases/paragraphes", "Temps de lecture estimé", "Fréquence des mots", "Indice de lisibilité"],
        guide: ["Collez ou saisissez votre texte dans la zone d'édition", "Les statistiques se mettent à jour instantanément", "Consultez les différents onglets pour des analyses approfondies"] },
      { title: "Formatage", url: "/text-formatter", desc: "Transformation de texte",
        shortDesc: "Transformez votre texte avec diverses opérations : tri de lignes, suppression de doublons, numérotation, etc.",
        features: ["Tri alphabétique des lignes", "Suppression des doublons", "Numérotation de lignes", "Inversion de lignes", "Trim et nettoyage"],
        guide: ["Entrez votre texte dans la zone de saisie", "Sélectionnez la transformation souhaitée", "Le résultat s'affiche en temps réel", "Copiez le résultat transformé"] },
      { title: "Extracteur", url: "/data-extractor", desc: "Extraction de données",
        shortDesc: "Extrayez automatiquement les emails, URLs, numéros de téléphone et autres données structurées d'un texte brut.",
        features: ["Extraction d'emails", "Extraction d'URLs", "Extraction de numéros", "Extraction d'adresses IP", "Export des résultats"],
        guide: ["Collez votre texte source dans la zone de saisie", "Sélectionnez le type de données à extraire", "Les résultats s'affichent instantanément", "Copiez ou exportez les données extraites"] },
      { title: "Lorem Ipsum", url: "/lorem", desc: "Génération de texte",
        shortDesc: "Générez du texte Lorem Ipsum en paragraphes, phrases ou mots pour vos maquettes et prototypes.",
        features: ["Génération par paragraphes, phrases ou mots", "Nombre personnalisable", "Copie en un clic", "Plusieurs variantes de texte"],
        guide: ["Choisissez le type de génération (paragraphes, phrases, mots)", "Définissez la quantité souhaitée", "Cliquez sur Générer", "Copiez le résultat"] },
      { title: "Nettoyeur", url: "/text-cleaner", desc: "Nettoyage de texte",
        shortDesc: "Nettoyez votre texte en supprimant les espaces superflus, caractères invisibles, lignes vides et formatages indésirables.",
        features: ["Suppression des espaces multiples", "Nettoyage des caractères invisibles", "Suppression des lignes vides", "Normalisation des sauts de ligne"],
        guide: ["Collez le texte à nettoyer", "Cochez les options de nettoyage souhaitées", "Le texte nettoyé s'affiche en temps réel", "Copiez le résultat"] },
      { title: "Convertisseur", url: "/format-converter", desc: "JSON, YAML, XML…",
        shortDesc: "Convertissez instantanément entre les formats JSON, YAML, XML et TOML avec validation intégrée.",
        features: ["Conversion JSON ↔ YAML", "Conversion JSON ↔ XML", "Support TOML", "Validation du format source", "Formatage automatique"],
        guide: ["Collez vos données dans le panneau source", "Sélectionnez le format d'entrée et le format de sortie", "La conversion s'effectue automatiquement", "Copiez le résultat converti"] },
      { title: "HTML ↔ Markdown", url: "/html-md", desc: "Conversion bidirectionnelle",
        shortDesc: "Convertissez bidirectionnellement entre HTML et Markdown avec prévisualisation en temps réel.",
        features: ["Conversion HTML vers Markdown", "Conversion Markdown vers HTML", "Prévisualisation du rendu", "Support des tableaux et listes"],
        guide: ["Saisissez du HTML ou du Markdown dans le panneau source", "Choisissez la direction de conversion", "Le résultat s'affiche instantanément", "Copiez le code converti"] },
      { title: "Text Case", url: "/text-case", desc: "Majuscules, camelCase…",
        shortDesc: "Convertissez la casse de votre texte : MAJUSCULES, minuscules, camelCase, snake_case, Title Case et plus.",
        features: ["MAJUSCULES / minuscules", "camelCase / PascalCase", "snake_case / kebab-case", "Title Case / Sentence case"],
        guide: ["Saisissez ou collez votre texte", "Cliquez sur la transformation de casse souhaitée", "Le résultat s'affiche instantanément", "Copiez le texte transformé"] },
      { title: "Encodage", url: "/char-encoding", desc: "UTF-8, entités HTML",
        shortDesc: "Explorez et convertissez les encodages de caractères : UTF-8, entités HTML, codes Unicode et plus.",
        features: ["Conversion entités HTML", "Lookup Unicode", "Table des caractères", "Encodage/décodage URL"],
        guide: ["Saisissez un caractère ou une chaîne", "Consultez ses différentes représentations", "Convertissez entre les formats d'encodage", "Copiez l'encodage souhaité"] },
      { title: "Word Counter", url: "/word-counter", desc: "Compteur, lisibilité",
        shortDesc: "Compteur de mots avancé avec indice de lisibilité, densité de mots-clés et statistiques détaillées.",
        features: ["Comptage mots/caractères en temps réel", "Indice de lisibilité Flesch", "Densité de mots-clés", "Temps de lecture/parole estimé"],
        guide: ["Collez ou saisissez votre texte", "Les statistiques se mettent à jour automatiquement", "Consultez les analyses de lisibilité", "Exportez le rapport si nécessaire"] },
      { title: "Table Generator", url: "/table-generator", desc: "Tableaux MD/HTML/CSV",
        shortDesc: "Créez des tableaux et exportez-les en Markdown, HTML ou CSV avec un éditeur visuel intuitif.",
        features: ["Éditeur visuel de tableaux", "Export Markdown / HTML / CSV", "Ajout/suppression de lignes et colonnes", "Alignement des colonnes"],
        guide: ["Définissez le nombre de lignes et colonnes", "Remplissez les cellules du tableau", "Choisissez le format d'export", "Copiez le code généré"] },
      { title: "Readme Generator", url: "/readme-generator", desc: "README.md professionnel",
        shortDesc: "Générez un README.md professionnel et structuré pour vos projets avec un formulaire guidé.",
        features: ["Sections prédéfinies (Installation, Usage, API…)", "Badges automatiques", "Table des matières", "Preview Markdown"],
        guide: ["Remplissez les informations de votre projet", "Sélectionnez les sections à inclure", "Personnalisez le contenu de chaque section", "Copiez le README généré"] },
    ],
  },
  {
    label: "Code & Analyse",
    items: [
      { title: "Regex Pro", url: "/regex", desc: "Test et debug regex",
        shortDesc: "Testez, déboguez et visualisez vos expressions régulières en temps réel avec coloration syntaxique et groupes de capture.",
        features: ["Test temps réel avec highlighting des matches", "Affichage des groupes de capture", "Drapeaux configurables (g, i, m, s)", "Bibliothèque de patterns courants", "Explication visuelle de la regex"],
        guide: ["Saisissez votre expression régulière dans le champ du haut", "Entrez le texte de test dans la zone en dessous", "Les correspondances sont surlignées automatiquement", "Consultez les groupes de capture dans le panneau de résultats"] },
      { title: "JSON/YAML", url: "/json", desc: "Validation et formatage",
        shortDesc: "Validez, formatez et explorez du JSON ou YAML avec arbre interactif et détection d'erreurs.",
        features: ["Validation JSON/YAML", "Formatage avec indentation configurable", "Vue en arbre interactive", "Détection d'erreurs avec position"],
        guide: ["Collez votre JSON ou YAML dans l'éditeur", "Les erreurs de syntaxe sont signalées en temps réel", "Utilisez le bouton Formater pour indenter proprement", "Explorez la structure via la vue arborescente"] },
      { title: "SQL Formatter", url: "/sql", desc: "Formatage SQL",
        shortDesc: "Formatez et embellissez vos requêtes SQL avec indentation automatique et coloration syntaxique.",
        features: ["Formatage automatique", "Coloration syntaxique", "Support multi-dialectes", "Minification"],
        guide: ["Collez votre requête SQL brute", "Cliquez sur Formater", "Ajustez les options d'indentation si nécessaire", "Copiez la requête formatée"] },
      { title: "CSS Formatter", url: "/css-formatter", desc: "Formatage CSS",
        shortDesc: "Formatez, embellissez ou minifiez votre code CSS avec support des propriétés imbriquées et media queries.",
        features: ["Formatage CSS", "Minification", "Tri des propriétés", "Support des preprocessors"],
        guide: ["Collez votre code CSS", "Choisissez entre embellir ou minifier", "Le résultat s'affiche instantanément", "Copiez le CSS formaté"] },
      { title: "XML Formatter", url: "/xml", desc: "Formatage XML",
        shortDesc: "Formatez et validez votre XML avec indentation automatique et détection d'erreurs de syntaxe.",
        features: ["Formatage avec indentation", "Validation de la syntaxe", "Minification", "Coloration syntaxique"],
        guide: ["Collez votre XML dans l'éditeur", "Cliquez sur Formater pour indenter", "Les erreurs de syntaxe sont signalées", "Copiez le résultat"] },
      { title: "Escape/Unescape", url: "/escape", desc: "Encodage multi-formats",
        shortDesc: "Échappez ou désechappez des chaînes pour JSON, HTML, URL, XML, SQL et d'autres formats courants.",
        features: ["Escape/Unescape JSON", "Encodage/décodage HTML", "Encodage/décodage URL", "Escape SQL", "Escape XML"],
        guide: ["Saisissez votre texte à encoder/décoder", "Sélectionnez le format cible", "Le résultat s'affiche instantanément", "Copiez la chaîne échappée"] },
      { title: "Base64", url: "/base64", desc: "Encodage/décodage",
        shortDesc: "Encodez ou décodez du texte et des fichiers en Base64 avec support des images et preview intégrée.",
        features: ["Encodage/décodage texte", "Support des fichiers et images", "Preview des images Base64", "Data URI generation"],
        guide: ["Collez du texte ou un fichier à encoder", "Ou collez du Base64 à décoder", "Le résultat s'affiche en temps réel", "Copiez l'encodage ou le décodage"] },
      { title: "JWT Decoder", url: "/jwt", desc: "Décodage tokens",
        shortDesc: "Décodez et inspectez les tokens JWT : header, payload, signature, dates d'expiration et claims.",
        features: ["Décodage header et payload", "Vérification d'expiration", "Affichage des claims standards", "Coloration syntaxique JSON"],
        guide: ["Collez votre token JWT complet", "Le header et le payload sont décodés automatiquement", "Vérifiez les dates d'expiration", "Inspectez les claims personnalisés"] },
      { title: "API Tester", url: "/api-tester", desc: "Test d'APIs REST",
        shortDesc: "Testez des APIs REST directement depuis le navigateur avec support des méthodes HTTP, headers et body.",
        features: ["Support GET, POST, PUT, DELETE, PATCH", "Éditeur de headers personnalisés", "Body JSON/Form/Raw", "Affichage de la réponse formatée", "Historique des requêtes"],
        guide: ["Entrez l'URL de l'API à tester", "Sélectionnez la méthode HTTP", "Ajoutez les headers et le body si nécessaire", "Cliquez sur Envoyer et inspectez la réponse"] },
      { title: "Code Minifier", url: "/code-minifier", desc: "Minification",
        shortDesc: "Minifiez votre code JavaScript, CSS et HTML pour réduire la taille des fichiers de production.",
        features: ["Minification JS/CSS/HTML", "Affichage du gain de taille", "Suppression commentaires et whitespace", "Comparaison avant/après"],
        guide: ["Collez votre code source", "Sélectionnez le langage", "Cliquez sur Minifier", "Copiez le code minifié et vérifiez le gain"] },
      { title: "GraphQL Tester", url: "/graphql", desc: "Test GraphQL",
        shortDesc: "Testez vos requêtes GraphQL avec un éditeur intégré, variables, headers et exploration du schéma.",
        features: ["Éditeur de requêtes GraphQL", "Support des variables", "Headers personnalisés", "Affichage des résultats formatés"],
        guide: ["Entrez l'URL de votre endpoint GraphQL", "Rédigez votre query ou mutation", "Ajoutez les variables si nécessaire", "Exécutez et inspectez la réponse"] },
      { title: "WebSocket Tester", url: "/websocket", desc: "Test WebSockets",
        shortDesc: "Connectez-vous à un serveur WebSocket, envoyez des messages et visualisez les échanges en temps réel.",
        features: ["Connexion WebSocket", "Envoi/réception de messages", "Historique des échanges", "Support des protocoles personnalisés"],
        guide: ["Entrez l'URL WebSocket (ws:// ou wss://)", "Cliquez sur Connecter", "Envoyez des messages via le champ de saisie", "Consultez les messages reçus dans le log"] },
      { title: "Cron Builder", url: "/cron", desc: "Expressions cron",
        shortDesc: "Construisez visuellement des expressions cron avec prévisualisation des prochaines exécutions.",
        features: ["Builder visuel par champs", "Prévisualisation des exécutions", "Support syntaxe standard et Quartz", "Exemples courants"],
        guide: ["Configurez chaque champ via les sélecteurs visuels", "Ou saisissez directement l'expression cron", "Vérifiez les prochaines exécutions", "Copiez l'expression finale"] },
      { title: "AST Explorer", url: "/ast", desc: "Arbre syntaxique",
        shortDesc: "Visualisez l'arbre syntaxique abstrait (AST) de votre code JavaScript/TypeScript pour comprendre sa structure.",
        features: ["Parsing JavaScript/TypeScript", "Vue arborescente interactive", "Highlight du nœud sélectionné", "Détails des propriétés de chaque nœud"],
        guide: ["Collez votre code source dans l'éditeur", "L'AST est généré automatiquement", "Cliquez sur un nœud pour voir ses détails", "Explorez la hiérarchie de l'arbre"] },
      { title: "Package Analyzer", url: "/package-analyzer", desc: "Analyse npm",
        shortDesc: "Analysez un package.json pour visualiser les dépendances, scripts, métadonnées et problèmes potentiels.",
        features: ["Analyse des dépendances", "Visualisation des scripts", "Détection des problèmes", "Informations du package"],
        guide: ["Collez le contenu de votre package.json", "L'analyse démarre automatiquement", "Consultez les différents onglets d'informations", "Identifiez les dépendances obsolètes ou problématiques"] },
      { title: "Prompt Engineer", url: "/prompt-engineer", desc: "Conception LLM",
        shortDesc: "Concevez et optimisez vos prompts pour les modèles d'IA avec des templates, techniques et bonnes pratiques.",
        features: ["Templates de prompts", "Techniques de prompting", "Variables dynamiques", "Test et itération", "Bibliothèque d'exemples"],
        guide: ["Choisissez un template ou partez de zéro", "Rédigez votre prompt avec les techniques recommandées", "Utilisez les variables pour paramétrer", "Testez et affinez votre prompt"] },
      { title: "TOML Editor", url: "/toml-editor", desc: "Éditeur TOML/INI",
        shortDesc: "Éditez et validez des fichiers TOML et INI avec coloration syntaxique et conversion vers JSON/YAML.",
        features: ["Édition TOML avec validation", "Conversion TOML ↔ JSON", "Coloration syntaxique", "Détection d'erreurs"],
        guide: ["Collez ou saisissez votre fichier TOML", "Les erreurs de syntaxe sont signalées", "Convertissez vers d'autres formats si nécessaire", "Copiez le résultat"] },
      { title: "Mermaid Editor", url: "/mermaid-editor", desc: "Diagrammes Mermaid",
        shortDesc: "Créez des diagrammes (flowcharts, séquences, Gantt…) avec la syntaxe Mermaid et prévisualisation live.",
        features: ["Support flowcharts, séquences, Gantt", "Prévisualisation en temps réel", "Export en image", "Exemples intégrés"],
        guide: ["Saisissez votre code Mermaid dans l'éditeur", "Le diagramme se génère automatiquement", "Utilisez les exemples comme point de départ", "Exportez le diagramme en image"] },
      { title: "Bundle Analyzer", url: "/bundle-analyzer", desc: "Taille de bundle",
        shortDesc: "Estimez la taille de vos dépendances npm et analysez l'impact sur votre bundle de production.",
        features: ["Estimation de taille des packages", "Comparaison de packages", "Analyse des dépendances transitives", "Alternatives suggérées"],
        guide: ["Entrez le nom d'un package npm", "Consultez la taille estimée (min+gzip)", "Comparez plusieurs packages", "Identifiez les alternatives plus légères"] },
      { title: "HTTP Headers", url: "/http-headers", desc: "Analyseur headers",
        shortDesc: "Analysez et comprenez les headers HTTP avec descriptions détaillées, exemples et bonnes pratiques de sécurité.",
        features: ["Référence complète des headers", "Catégorisation par type", "Exemples de valeurs", "Recommandations de sécurité"],
        guide: ["Parcourez la liste des headers HTTP", "Cliquez sur un header pour voir ses détails", "Consultez les exemples et valeurs recommandées", "Appliquez les recommandations de sécurité"] },
      { title: "Tailwind ↔ CSS", url: "/tailwind-css", desc: "Convertisseur",
        shortDesc: "Convertissez des classes Tailwind CSS en CSS vanilla et inversement pour faciliter vos migrations.",
        features: ["Tailwind vers CSS vanilla", "CSS vers classes Tailwind", "Support des classes responsive", "Copie rapide"],
        guide: ["Collez vos classes Tailwind ou votre CSS", "Sélectionnez la direction de conversion", "Le résultat s'affiche en temps réel", "Copiez le code converti"] },
      { title: "Dep Graph", url: "/dep-graph", desc: "Graphe dépendances",
        shortDesc: "Visualisez le graphe de dépendances de votre projet à partir du package.json sous forme de diagramme interactif.",
        features: ["Graphe visuel des dépendances", "Distinction deps/devDeps", "Vue hiérarchique", "Informations sur chaque package"],
        guide: ["Collez votre package.json", "Le graphe de dépendances se génère", "Explorez les relations entre packages", "Identifiez les dépendances critiques"] },
      { title: "Docker Compose", url: "/docker-compose", desc: "docker-compose.yml",
        shortDesc: "Construisez visuellement un fichier docker-compose.yml avec des services, volumes, réseaux et variables d'environnement.",
        features: ["Builder visuel de services", "Configuration des volumes et réseaux", "Variables d'environnement", "Export YAML", "Templates prédéfinis"],
        guide: ["Ajoutez des services avec le builder", "Configurez les ports, volumes et variables", "Utilisez les templates pour démarrer rapidement", "Exportez le fichier docker-compose.yml"] },
      { title: "Webhook Tester", url: "/webhook-tester", desc: "Webhooks",
        shortDesc: "Testez et déboguez des webhooks en envoyant des requêtes HTTP personnalisées avec headers et payload.",
        features: ["Envoi de webhooks personnalisés", "Support de tous les verbes HTTP", "Headers et body configurables", "Historique des envois"],
        guide: ["Entrez l'URL du webhook cible", "Configurez la méthode, les headers et le body", "Envoyez la requête", "Inspectez la réponse reçue"] },
      { title: "NPM Compare", url: "/npm-compare", desc: "Comparaison packages",
        shortDesc: "Comparez des packages npm côte à côte : taille, popularité, maintenance, dépendances et tendances.",
        features: ["Comparaison multi-packages", "Statistiques de téléchargements", "Taille et dépendances", "Score de qualité"],
        guide: ["Entrez les noms des packages à comparer", "Consultez les métriques côte à côte", "Analysez les tendances de téléchargement", "Choisissez le package le plus adapté"] },
      { title: "Server Config", url: "/server-config", desc: "Nginx/Apache",
        shortDesc: "Générez des configurations serveur Nginx ou Apache pour vos cas d'usage courants (proxy, SSL, cache…).",
        features: ["Génération Nginx / Apache", "Templates courants (proxy, SSL, cache)", "Configuration personnalisable", "Export du fichier de config"],
        guide: ["Choisissez le serveur (Nginx ou Apache)", "Sélectionnez le type de configuration", "Personnalisez les paramètres", "Copiez la configuration générée"] },
      { title: "SQL ↔ Prisma", url: "/sql-prisma", desc: "Conversion",
        shortDesc: "Convertissez entre des schémas SQL et des modèles Prisma pour faciliter vos migrations ORM.",
        features: ["SQL vers Prisma schema", "Prisma vers SQL", "Support des relations", "Détection des types"],
        guide: ["Collez votre schéma SQL ou Prisma", "Sélectionnez la direction de conversion", "Le résultat s'affiche en temps réel", "Copiez le schéma converti"] },
      { title: "API Docs", url: "/api-docs", desc: "Documentation OpenAPI",
        shortDesc: "Générez une documentation API interactive à partir d'une spécification OpenAPI/Swagger.",
        features: ["Parsing OpenAPI 3.x", "Documentation interactive", "Exemples de requêtes/réponses", "Export de la documentation"],
        guide: ["Collez votre spécification OpenAPI en JSON ou YAML", "La documentation se génère automatiquement", "Naviguez entre les endpoints", "Consultez les schémas et exemples"] },
      { title: "Code Formatter", url: "/code-formatter", desc: "Formatage multi-lang",
        shortDesc: "Formatez du code dans plusieurs langages (JS, TS, HTML, CSS, JSON, SQL) avec un formatage standardisé.",
        features: ["Support multi-langages", "Formatage standardisé", "Options d'indentation", "Copie rapide"],
        guide: ["Collez votre code dans l'éditeur", "Sélectionnez le langage", "Cliquez sur Formater", "Copiez le code formaté"] },
    ],
  },
  {
    label: "Design",
    items: [
      { title: "Couleurs", url: "/colors", desc: "Sélecteur et palettes",
        shortDesc: "Sélecteur de couleurs avancé avec conversion HEX/RGB/HSL, palettes prédéfinies et copie rapide.",
        features: ["Sélecteur visuel de couleurs", "Conversion HEX / RGB / HSL / HSB", "Palettes prédéfinies", "Historique des couleurs", "Copie rapide en un clic"],
        guide: ["Utilisez le sélecteur visuel ou entrez un code couleur", "Naviguez entre les onglets de format", "Cliquez sur une couleur pour la copier", "Consultez les palettes prédéfinies pour l'inspiration"] },
      { title: "Gradients CSS", url: "/gradients", desc: "Dégradés",
        shortDesc: "Créez des dégradés CSS linéaires, radiaux et coniques avec un éditeur visuel et copie du code CSS.",
        features: ["Dégradés linéaires, radiaux, coniques", "Ajout de color stops", "Angle et direction configurables", "Copie du code CSS généré"],
        guide: ["Choisissez le type de dégradé", "Ajoutez et déplacez les color stops", "Ajustez l'angle ou la direction", "Copiez le code CSS"] },
      { title: "Box Shadow", url: "/box-shadow", desc: "Ombres",
        shortDesc: "Créez des ombres CSS (box-shadow) avec un éditeur visuel intuitif et prévisualisation en temps réel.",
        features: ["Éditeur visuel d'ombres", "Ombres multiples", "Inset shadow", "Prévisualisation live", "Copie CSS"],
        guide: ["Ajustez les sliders pour X, Y, blur et spread", "Choisissez la couleur de l'ombre", "Ajoutez plusieurs ombres si nécessaire", "Copiez le code CSS généré"] },
      { title: "Border Radius", url: "/border-radius", desc: "Coins arrondis",
        shortDesc: "Personnalisez le border-radius de vos éléments avec un éditeur visuel et prévisualisation instantanée.",
        features: ["Contrôle individuel de chaque coin", "Prévisualisation en temps réel", "Valeurs en px ou %", "Copie du code CSS"],
        guide: ["Ajustez les sliders pour chaque coin", "Ou entrez les valeurs directement", "Visualisez le résultat en temps réel", "Copiez le code CSS"] },
      { title: "Text Shadow", url: "/text-shadow", desc: "Ombres de texte",
        shortDesc: "Créez des ombres de texte CSS (text-shadow) avec un éditeur visuel et prévisualisation sur texte personnalisable.",
        features: ["Éditeur visuel d'ombres de texte", "Ombres multiples", "Texte de prévisualisation personnalisable", "Copie CSS"],
        guide: ["Ajustez les paramètres d'ombre (X, Y, blur, couleur)", "Personnalisez le texte de prévisualisation", "Ajoutez plusieurs ombres pour des effets avancés", "Copiez le code CSS"] },
      { title: "Animations CSS", url: "/css-animations", desc: "Animations",
        shortDesc: "Créez des animations CSS avec un éditeur visuel de keyframes, courbes d'accélération et prévisualisation live.",
        features: ["Éditeur de keyframes", "Courbes de timing personnalisables", "Animations prédéfinies", "Prévisualisation en temps réel", "Export CSS"],
        guide: ["Choisissez une animation prédéfinie ou créez la vôtre", "Configurez les keyframes et la durée", "Ajustez la courbe d'accélération", "Prévisualisez et copiez le CSS"] },
      { title: "Flexbox", url: "/flexbox", desc: "Playground Flexbox",
        shortDesc: "Expérimentez avec CSS Flexbox dans un playground interactif pour comprendre et maîtriser les propriétés flex.",
        features: ["Contrôle de toutes les propriétés flex", "Prévisualisation en temps réel", "Ajout/suppression d'éléments enfants", "Code CSS généré"],
        guide: ["Ajustez les propriétés du container flex", "Modifiez les propriétés des éléments enfants", "Observez les changements en temps réel", "Copiez le CSS pour votre projet"] },
      { title: "CSS Grid", url: "/grid", desc: "Grilles CSS",
        shortDesc: "Construisez des layouts CSS Grid avec un éditeur visuel interactif et génération automatique du code.",
        features: ["Définition de colonnes et rangées", "Placement des éléments", "Gap configurable", "Templates prédéfinis", "Code CSS généré"],
        guide: ["Définissez vos colonnes et rangées", "Placez les éléments dans la grille", "Ajustez les gaps et alignements", "Copiez le code CSS Grid"] },
      { title: "Contraste WCAG", url: "/contrast", desc: "Vérificateur",
        shortDesc: "Vérifiez le contraste entre deux couleurs selon les normes WCAG AA et AAA pour l'accessibilité web.",
        features: ["Calcul du ratio de contraste", "Validation WCAG AA / AAA", "Test texte normal et large", "Suggestions de couleurs conformes"],
        guide: ["Saisissez la couleur du texte", "Saisissez la couleur de fond", "Consultez le ratio de contraste", "Vérifiez la conformité WCAG AA/AAA"] },
      { title: "Icônes SVG", url: "/svg-icons", desc: "Bibliothèque",
        shortDesc: "Parcourez et copiez des icônes SVG provenant de bibliothèques populaires avec recherche et personnalisation.",
        features: ["Bibliothèque d'icônes Lucide", "Recherche par nom", "Personnalisation taille et couleur", "Copie SVG / JSX"],
        guide: ["Recherchez une icône par nom ou mot-clé", "Personnalisez la taille et la couleur", "Cliquez pour copier le SVG ou JSX", "Collez dans votre projet"] },
      { title: "Espacements", url: "/spacing", desc: "Calculateur spacing",
        shortDesc: "Calculez et visualisez des systèmes d'espacement cohérents basés sur un facteur d'échelle pour vos designs.",
        features: ["Échelle d'espacements configurable", "Visualisation des valeurs", "Export en CSS/Tailwind", "Prévisualisation visuelle"],
        guide: ["Définissez la valeur de base et le facteur d'échelle", "Consultez l'échelle d'espacements générée", "Visualisez les espacements", "Copiez les valeurs pour votre projet"] },
      { title: "Font Pairing", url: "/font-pairing", desc: "Combinaisons polices",
        shortDesc: "Découvrez des combinaisons de polices harmonieuses pour vos projets avec prévisualisation en temps réel.",
        features: ["Pairings recommandés", "Prévisualisation sur texte réel", "Google Fonts intégrés", "Personnalisation des tailles"],
        guide: ["Parcourez les combinaisons suggérées", "Prévisualisez sur votre propre texte", "Ajustez les tailles et graisses", "Copiez le code d'import des polices"] },
      { title: "Responsive Preview", url: "/responsive-preview", desc: "Prévisualisation",
        shortDesc: "Prévisualisez n'importe quelle URL dans différentes tailles d'écran (mobile, tablette, desktop) simultanément.",
        features: ["Prévisualisation multi-appareils", "Tailles personnalisables", "URL personnalisable", "Vue côte à côte"],
        guide: ["Entrez l'URL à prévisualiser", "Consultez le rendu sur différents appareils", "Ajustez les dimensions si nécessaire", "Vérifiez le responsive design"] },
      { title: "CSS Specificity", url: "/css-specificity", desc: "Spécificité",
        shortDesc: "Calculez et comparez la spécificité de vos sélecteurs CSS pour comprendre la cascade et résoudre les conflits.",
        features: ["Calcul de spécificité", "Comparaison de sélecteurs", "Explication visuelle", "Référence des règles"],
        guide: ["Saisissez un ou plusieurs sélecteurs CSS", "Consultez le score de spécificité", "Comparez les sélecteurs entre eux", "Comprenez pourquoi un style prend le dessus"] },
      { title: "A11y Checklist", url: "/a11y-checklist", desc: "Audit WCAG",
        shortDesc: "Parcourez une checklist complète des critères d'accessibilité WCAG pour auditer votre site web.",
        features: ["Critères WCAG 2.1 organisés", "Checklist interactive", "Filtres par niveau (A, AA, AAA)", "Descriptions et exemples"],
        guide: ["Parcourez les critères d'accessibilité", "Cochez les critères que votre site respecte", "Filtrez par niveau de conformité", "Consultez les exemples pour chaque critère"] },
      { title: "Glassmorphism", url: "/glassmorphism", desc: "Effets verre",
        shortDesc: "Créez des effets de verre dépoli (glassmorphism) avec un éditeur visuel et génération du code CSS.",
        features: ["Contrôle du blur et de la transparence", "Bordure et opacité configurables", "Fond personnalisable", "Copie CSS"],
        guide: ["Ajustez le flou et la transparence", "Personnalisez la couleur de fond", "Configurez la bordure", "Copiez le code CSS"] },
      { title: "Clip-path Editor", url: "/clip-path", desc: "Formes CSS",
        shortDesc: "Créez des formes CSS avec clip-path via un éditeur visuel de polygones, cercles et ellipses.",
        features: ["Éditeur visuel de formes", "Polygones, cercles, ellipses", "Formes prédéfinies", "Code CSS clip-path"],
        guide: ["Choisissez un type de forme ou un preset", "Ajustez les points visuellement", "Prévisualisez le résultat", "Copiez le code CSS clip-path"] },
      { title: "Color Palette", url: "/color-palette", desc: "Palettes harmoniques",
        shortDesc: "Générez des palettes de couleurs harmoniques (complémentaire, triadique, analogue…) à partir d'une couleur de base.",
        features: ["Harmonie complémentaire, triadique, analogue", "Nuances et teintes", "Export des palettes", "Codes couleurs multiples"],
        guide: ["Choisissez une couleur de base", "Sélectionnez le type d'harmonie", "Explorez les variations générées", "Exportez la palette"] },
      { title: "CSS Filter", url: "/css-filter", desc: "Filtres CSS",
        shortDesc: "Appliquez et combinez des filtres CSS (blur, brightness, contrast, grayscale…) avec prévisualisation live.",
        features: ["Filtres CSS complets", "Combinaison de filtres", "Prévisualisation en temps réel", "Copie du code CSS"],
        guide: ["Ajustez les sliders de chaque filtre", "Combinez plusieurs filtres", "Prévisualisez le résultat", "Copiez le code CSS filter"] },
      { title: "Type Scale", url: "/type-scale", desc: "Échelle typo",
        shortDesc: "Générez une échelle typographique harmonieuse basée sur un ratio et une taille de base pour votre design system.",
        features: ["Ratios prédéfinis (Golden, Perfect Fourth…)", "Taille de base configurable", "Prévisualisation des tailles", "Export CSS/Tailwind"],
        guide: ["Choisissez un ratio d'échelle", "Définissez la taille de base", "Consultez l'échelle générée", "Copiez les valeurs CSS ou Tailwind"] },
      { title: "CSS Variables", url: "/css-variables", desc: "Thème CSS",
        shortDesc: "Générez un système de CSS custom properties (variables) pour créer des thèmes cohérents et maintenables.",
        features: ["Génération de variables CSS", "Thèmes clair/sombre", "Palette complète", "Export CSS"],
        guide: ["Définissez vos couleurs principales", "Configurez les variantes", "Prévisualisez le thème", "Copiez les variables CSS"] },
      { title: "Tailwind Playground", url: "/tailwind-playground", desc: "Sandbox Tailwind",
        shortDesc: "Expérimentez avec les classes Tailwind CSS dans un playground interactif avec prévisualisation en temps réel.",
        features: ["Éditeur avec autocomplétion", "Prévisualisation live", "Référence des classes", "Reset et partage"],
        guide: ["Saisissez des classes Tailwind dans l'éditeur", "Observez le résultat dans la prévisualisation", "Consultez la référence des classes disponibles", "Expérimentez librement"] },
    ],
  },
  {
    label: "Utilitaires",
    items: [
      { title: "Mot de passe", url: "/password", desc: "Générateur sécurisé",
        shortDesc: "Générez des mots de passe sécurisés avec contrôle de la longueur, complexité et indicateur de force.",
        features: ["Longueur personnalisable", "Options majuscules/minuscules/chiffres/symboles", "Indicateur de force", "Copie en un clic", "Génération multiple"],
        guide: ["Définissez la longueur souhaitée", "Sélectionnez les types de caractères à inclure", "Générez un ou plusieurs mots de passe", "Copiez le mot de passe choisi"] },
      { title: "Hash", url: "/hash", desc: "MD5, SHA-256…",
        shortDesc: "Calculez des empreintes cryptographiques (MD5, SHA-256, SHA-512, BLAKE2…) pour du texte ou des fichiers.",
        features: ["Support MD5, SHA-1, SHA-256, SHA-512", "SHA3, BLAKE2b, BLAKE2s, RIPEMD-160", "Hash de fichiers", "HMAC avec clé secrète", "Vérification de hash", "Export CSV/JSON"],
        guide: ["Saisissez le texte ou chargez un fichier", "Sélectionnez les algorithmes à utiliser", "Les hash se calculent en temps réel", "Comparez ou exportez les résultats"] },
      { title: "Unités & Mesures", url: "/converters", desc: "Convertisseurs",
        shortDesc: "Convertissez entre différentes unités de mesure : longueur, poids, température, vitesse, données et plus.",
        features: ["Longueur, poids, température", "Vitesse, surface, volume", "Données (octets, Ko, Mo…)", "Conversion bidirectionnelle"],
        guide: ["Sélectionnez la catégorie d'unités", "Entrez une valeur dans l'unité source", "Choisissez l'unité cible", "Le résultat s'affiche instantanément"] },
      { title: "UUID Generator", url: "/uuid", desc: "Identifiants",
        shortDesc: "Générez des identifiants uniques UUID v4 en lot avec copie rapide et options de formatage.",
        features: ["Génération UUID v4", "Génération en lot", "Copie individuelle ou groupée", "Options de formatage"],
        guide: ["Définissez le nombre d'UUID à générer", "Cliquez sur Générer", "Copiez les UUID individuellement ou en lot", "Utilisez les options de format si nécessaire"] },
      { title: "QR Code", url: "/qrcode", desc: "Générateur QR",
        shortDesc: "Générez des QR codes personnalisables à partir de texte ou d'URL avec options de couleur et taille.",
        features: ["Génération depuis texte/URL", "Couleurs personnalisables", "Taille ajustable", "Téléchargement PNG"],
        guide: ["Saisissez le texte ou l'URL", "Personnalisez les couleurs si souhaité", "Ajustez la taille", "Téléchargez le QR code en PNG"] },
      { title: "Meta Tags", url: "/meta-tags", desc: "Générateur SEO",
        shortDesc: "Générez les meta tags HTML essentiels pour le SEO, Open Graph et Twitter Cards avec prévisualisation.",
        features: ["Meta tags HTML classiques", "Open Graph (Facebook)", "Twitter Cards", "Prévisualisation des résultats de recherche"],
        guide: ["Remplissez le titre, la description et l'URL", "Configurez les tags Open Graph", "Ajoutez les Twitter Cards", "Copiez le code HTML des meta tags"] },
      { title: "Slug Generator", url: "/slug", desc: "URLs propres",
        shortDesc: "Transformez n'importe quel texte en slug URL-friendly avec translittération et personnalisation du séparateur.",
        features: ["Génération de slugs", "Translittération des accents", "Séparateur configurable", "Copie rapide"],
        guide: ["Saisissez le texte à transformer", "Le slug est généré automatiquement", "Ajustez le séparateur si nécessaire", "Copiez le slug"] },
      { title: "TOTP / 2FA", url: "/totp-generator", desc: "Codes TOTP",
        shortDesc: "Générez et vérifiez des codes TOTP (Time-based One-Time Password) pour l'authentification à deux facteurs.",
        features: ["Génération de codes TOTP", "Compteur de temps restant", "Support des clés secrètes", "Vérification de codes"],
        guide: ["Entrez ou générez une clé secrète", "Le code TOTP se génère automatiquement", "Le compteur indique le temps restant", "Utilisez le code avant son expiration"] },
      { title: "Permissions Unix", url: "/unix-permissions", desc: "chmod",
        shortDesc: "Calculez et convertissez les permissions Unix (chmod) entre notation symbolique et octale avec explication.",
        features: ["Notation symbolique ↔ octale", "Sélecteur visuel (rwx)", "Explication de chaque permission", "Commande chmod générée"],
        guide: ["Cliquez sur les cases pour activer les permissions", "Ou entrez la valeur octale directement", "Consultez l'explication de chaque permission", "Copiez la commande chmod"] },
      { title: "Bases numériques", url: "/number-base", desc: "Binaire, hex…",
        shortDesc: "Convertissez des nombres entre les bases décimale, binaire, octale et hexadécimale instantanément.",
        features: ["Décimal, binaire, octal, hexadécimal", "Conversion bidirectionnelle", "Support des grands nombres", "Affichage groupé"],
        guide: ["Entrez un nombre dans n'importe quelle base", "Les conversions s'affichent automatiquement", "Utilisez le sélecteur de base d'entrée", "Copiez la valeur convertie souhaitée"] },
      { title: "URL Parser", url: "/url-parser", desc: "Analyse d'URLs",
        shortDesc: "Décomposez et analysez les composants d'une URL : protocole, domaine, chemin, paramètres et fragment.",
        features: ["Décomposition complète de l'URL", "Parsing des query parameters", "Encodage/décodage URL", "Reconstruction d'URL"],
        guide: ["Collez une URL complète", "Consultez la décomposition de chaque composant", "Modifiez les paramètres si nécessaire", "Copiez l'URL reconstruite"] },
      { title: "Env Manager", url: "/env-parser", desc: "Fichiers .env",
        shortDesc: "Éditez, validez et convertissez des fichiers .env avec détection des doublons et export multi-formats.",
        features: ["Parsing de fichiers .env", "Détection de doublons", "Validation des valeurs", "Export multi-formats"],
        guide: ["Collez le contenu de votre fichier .env", "Les variables sont parsées et listées", "Identifiez les doublons et erreurs", "Exportez dans le format souhaité"] },
      { title: "Timestamp", url: "/timestamp", desc: "Convertisseur",
        shortDesc: "Convertissez entre timestamps Unix et dates lisibles avec support des millisecondes et fuseaux horaires.",
        features: ["Timestamp ↔ date lisible", "Support secondes et millisecondes", "Fuseaux horaires multiples", "Timestamp actuel en temps réel"],
        guide: ["Entrez un timestamp ou une date", "La conversion s'affiche automatiquement", "Changez le fuseau horaire si nécessaire", "Copiez le résultat"] },
      { title: "IP Analyzer", url: "/ip-analyzer", desc: "Adresses IP",
        shortDesc: "Analysez des adresses IPv4/IPv6 : calcul de sous-réseaux, masques, plages et informations CIDR.",
        features: ["Analyse IPv4 et IPv6", "Calcul de sous-réseaux", "Masque et broadcast", "Notation CIDR"],
        guide: ["Entrez une adresse IP avec ou sans CIDR", "Consultez les informations de sous-réseau", "Vérifiez les plages d'adresses", "Utilisez les calculs de masque"] },
      { title: "Barcode", url: "/barcode", desc: "Codes-barres",
        shortDesc: "Générez des codes-barres dans différents formats (Code128, EAN, UPC…) avec personnalisation et export.",
        features: ["Formats Code128, EAN-13, UPC-A", "Personnalisation des couleurs", "Taille configurable", "Export PNG/SVG"],
        guide: ["Saisissez les données à encoder", "Choisissez le format de code-barres", "Personnalisez l'apparence", "Téléchargez le code-barres"] },
      { title: "Git Commit", url: "/git-commit", desc: "Commits conventionnels",
        shortDesc: "Générez des messages de commit Git conformes à la convention Conventional Commits avec un formulaire guidé.",
        features: ["Types de commit (feat, fix, chore…)", "Scope optionnel", "Breaking changes", "Copie de la commande git"],
        guide: ["Sélectionnez le type de commit", "Ajoutez le scope (optionnel)", "Rédigez la description", "Copiez le message de commit formaté"] },
      { title: "Changelog", url: "/changelog", desc: "Changelog",
        shortDesc: "Générez un fichier CHANGELOG.md structuré selon le standard Keep a Changelog avec un formulaire intuitif.",
        features: ["Format Keep a Changelog", "Sections Added/Changed/Fixed/Removed", "Versioning sémantique", "Export Markdown"],
        guide: ["Ajoutez une nouvelle version", "Remplissez les sections pertinentes", "Organisez les entrées par type", "Exportez le changelog en Markdown"] },
      { title: ".gitignore Builder", url: "/gitignore", desc: ".gitignore",
        shortDesc: "Construisez un fichier .gitignore personnalisé en sélectionnant des templates pour vos technologies et IDE.",
        features: ["Templates par technologie", "Templates par IDE/OS", "Combinaison multiple", "Règles personnalisées"],
        guide: ["Sélectionnez vos technologies et outils", "Les règles .gitignore se combinent automatiquement", "Ajoutez des règles personnalisées si nécessaire", "Copiez le fichier .gitignore"] },
      { title: "Favicon", url: "/favicon", desc: "Favicons",
        shortDesc: "Générez des favicons dans toutes les tailles nécessaires à partir d'un texte, emoji ou couleur personnalisée.",
        features: ["Génération depuis texte/emoji", "Toutes les tailles standards", "Couleur de fond personnalisable", "Code HTML des liens"],
        guide: ["Choisissez un emoji ou saisissez du texte", "Personnalisez la couleur de fond", "Prévisualisez le favicon", "Téléchargez les fichiers et copiez le HTML"] },
      { title: "Caractères Spéciaux", url: "/special-chars", desc: "Émojis, symboles",
        shortDesc: "Parcourez et copiez des émojis, symboles mathématiques, flèches et caractères spéciaux organisés par catégorie.",
        features: ["Émojis par catégorie", "Symboles mathématiques et techniques", "Flèches et formes", "Copie en un clic", "Recherche par nom"],
        guide: ["Parcourez les catégories de caractères", "Utilisez la recherche pour trouver un symbole", "Cliquez sur un caractère pour le copier", "Collez-le dans votre document"] },
      { title: "Robots.txt", url: "/robots-builder", desc: "robots.txt",
        shortDesc: "Construisez un fichier robots.txt avec un éditeur visuel pour contrôler l'indexation de votre site par les moteurs de recherche.",
        features: ["Éditeur visuel de règles", "User-agents prédéfinis", "Allow/Disallow configurables", "Sitemap intégrable"],
        guide: ["Ajoutez des règles par user-agent", "Configurez les chemins autorisés/interdits", "Ajoutez l'URL du sitemap", "Copiez le fichier robots.txt"] },
    ],
  },
  {
    label: "Dates & Temps",
    items: [
      { title: "Calculateur de dates", url: "/date-calculator", desc: "Calculs entre dates",
        shortDesc: "Calculez la différence entre deux dates ou ajoutez/soustrayez des jours, mois et années à une date.",
        features: ["Différence entre deux dates", "Ajout/soustraction de durées", "Résultat en jours/semaines/mois/années", "Jours ouvrés"],
        guide: ["Sélectionnez les deux dates à comparer", "Ou choisissez une date et ajoutez une durée", "Consultez le résultat détaillé", "Utilisez le mode jours ouvrés si nécessaire"] },
      { title: "Formats de date", url: "/date-formats", desc: "Conversion formats",
        shortDesc: "Convertissez une date entre différents formats (ISO 8601, RFC 2822, timestamp, formats locaux) en temps réel.",
        features: ["Formats ISO 8601, RFC 2822", "Formats locaux (FR, US, UK…)", "Timestamp Unix", "Formats personnalisés"],
        guide: ["Entrez une date dans n'importe quel format", "Consultez les conversions dans tous les formats", "Cliquez sur un format pour le copier", "Utilisez le format personnalisé si nécessaire"] },
      { title: "Inspecteur de dates", url: "/date-inspector", desc: "Analyse dates",
        shortDesc: "Analysez une date pour connaître le jour de la semaine, le numéro de semaine, le jour de l'année et plus.",
        features: ["Jour de la semaine", "Numéro de semaine ISO", "Jour de l'année", "Année bissextile", "Informations détaillées"],
        guide: ["Sélectionnez ou saisissez une date", "Consultez toutes les informations associées", "Vérifiez le numéro de semaine", "Identifiez les années bissextiles"] },
      { title: "Timezone", url: "/timezone", desc: "Fuseaux horaires",
        shortDesc: "Convertissez des heures entre fuseaux horaires et comparez l'heure actuelle dans différentes villes du monde.",
        features: ["Conversion entre fuseaux horaires", "Heure actuelle mondiale", "Recherche par ville/fuseau", "Calcul de décalage"],
        guide: ["Sélectionnez le fuseau source et cible", "Entrez l'heure à convertir", "Consultez l'heure dans le fuseau cible", "Comparez plusieurs fuseaux simultanément"] },
      { title: "Flux temporels", url: "/timelines", desc: "Timelines",
        shortDesc: "Créez des timelines visuelles pour planifier des événements et visualiser des séquences chronologiques.",
        features: ["Création de timelines", "Événements avec dates", "Visualisation chronologique", "Export"],
        guide: ["Ajoutez des événements avec leurs dates", "Organisez-les chronologiquement", "Visualisez la timeline générée", "Exportez si nécessaire"] },
      { title: "Calendriers", url: "/calendars", desc: "Jours fériés",
        shortDesc: "Consultez les calendriers avec jours fériés par pays et exportez-les au format ICS pour votre agenda.",
        features: ["Jours fériés par pays", "Vue calendrier mensuelle", "Export ICS", "Indication des weekends"],
        guide: ["Sélectionnez le pays et l'année", "Parcourez le calendrier mensuel", "Identifiez les jours fériés", "Exportez en ICS pour votre agenda"] },
      { title: "Date Reference", url: "/date-reference", desc: "Docs dates",
        shortDesc: "Référence complète des formats de dates, tokens de formatage et fonctions courantes pour les développeurs.",
        features: ["Tokens de formatage (YYYY, MM, DD…)", "Fonctions date-fns / Moment", "Formats standards", "Exemples de code"],
        guide: ["Parcourez les sections de la référence", "Consultez les tokens de formatage", "Copiez les exemples de code", "Utilisez comme aide-mémoire"] },
      { title: "Date Toolbox", url: "/date-toolbox", desc: "Validation",
        shortDesc: "Boîte à outils de validation et manipulation de dates : vérification de format, parsing et calculs rapides.",
        features: ["Validation de format de date", "Parsing intelligent", "Calculs rapides", "Détection du format"],
        guide: ["Entrez une date à valider", "Consultez le format détecté", "Effectuez des calculs rapides", "Vérifiez la validité de la date"] },
      { title: "Countdown", url: "/countdown", desc: "Minuteur",
        shortDesc: "Minuteur et compte à rebours personnalisable avec alertes sonores et affichage en plein écran.",
        features: ["Compte à rebours personnalisable", "Chronomètre", "Alerte sonore", "Mode plein écran"],
        guide: ["Définissez la durée du compte à rebours", "Ou utilisez le chronomètre", "Lancez le timer", "Recevez l'alerte à la fin"] },
    ],
  },
  {
    label: "Data & Backend",
    items: [
      { title: "Générateur de données", url: "/data-generator", desc: "Données test",
        shortDesc: "Générez des jeux de données de test réalistes (noms, emails, adresses…) en JSON, CSV ou SQL.",
        features: ["Types de données variés", "Formats JSON / CSV / SQL", "Nombre de lignes configurable", "Schéma personnalisable"],
        guide: ["Définissez les colonnes et leurs types", "Configurez le nombre de lignes", "Choisissez le format de sortie", "Générez et copiez les données"] },
      { title: "CSV Viewer", url: "/csv", desc: "Visualisation CSV",
        shortDesc: "Visualisez, triez et filtrez des fichiers CSV dans un tableau interactif avec détection automatique du délimiteur.",
        features: ["Tableau interactif", "Tri par colonne", "Filtrage des données", "Détection auto du délimiteur", "Statistiques de colonnes"],
        guide: ["Collez votre contenu CSV ou chargez un fichier", "Le tableau s'affiche automatiquement", "Cliquez sur les en-têtes pour trier", "Utilisez les filtres pour affiner"] },
      { title: "Schémas", url: "/schema-generator", desc: "Générateur schémas",
        shortDesc: "Générez des schémas de validation (JSON Schema, Zod, Yup) à partir d'exemples de données JSON.",
        features: ["JSON Schema", "Schémas Zod / Yup", "Inférence depuis JSON", "Validation intégrée"],
        guide: ["Collez un exemple de données JSON", "Le schéma est inféré automatiquement", "Choisissez le format de sortie", "Personnalisez et copiez le schéma"] },
      { title: "Faker Playground", url: "/faker-playground", desc: "Données réalistes",
        shortDesc: "Générez des données fictives réalistes avec Faker.js : noms, adresses, entreprises, lorem et plus.",
        features: ["Catégories Faker complètes", "Prévisualisation en temps réel", "Localisation française", "Copie rapide"],
        guide: ["Choisissez une catégorie Faker", "Sélectionnez le type de données", "Générez les données", "Copiez les résultats"] },
      { title: "SQL Builder", url: "/sql-builder", desc: "Constructeur requêtes",
        shortDesc: "Construisez des requêtes SQL visuellement avec un builder pour SELECT, INSERT, UPDATE et DELETE.",
        features: ["Builder visuel de requêtes", "Support SELECT/INSERT/UPDATE/DELETE", "Clauses WHERE, JOIN, ORDER BY", "Formatage automatique"],
        guide: ["Sélectionnez le type de requête", "Définissez les tables et colonnes", "Ajoutez les conditions et jointures", "Copiez la requête SQL générée"] },
      { title: "API Mocker Pro", url: "/mock-api", desc: "Mock endpoints",
        shortDesc: "Créez des endpoints d'API mock avec réponses personnalisées pour le développement et les tests frontend.",
        features: ["Endpoints configurables", "Réponses JSON personnalisées", "Latence simulable", "Codes de statut configurables"],
        guide: ["Définissez un endpoint (URL + méthode)", "Configurez la réponse JSON", "Ajoutez un délai si souhaité", "Utilisez l'URL mock dans votre code"] },
      { title: "DB Designer", url: "/db-designer", desc: "Schémas BDD",
        shortDesc: "Concevez visuellement des schémas de base de données avec tables, colonnes, relations et export SQL.",
        features: ["Éditeur visuel de tables", "Relations (1:1, 1:N, N:N)", "Types de colonnes", "Export SQL / diagramme"],
        guide: ["Ajoutez des tables", "Définissez les colonnes et types", "Créez les relations entre tables", "Exportez le schéma SQL"] },
      { title: "OpenAPI Designer", url: "/openapi-designer", desc: "APIs OpenAPI",
        shortDesc: "Concevez des APIs RESTful avec un éditeur OpenAPI 3.x visuel et génération de la spécification YAML/JSON.",
        features: ["Éditeur OpenAPI 3.x", "Définition des endpoints", "Schémas de requêtes/réponses", "Export YAML/JSON"],
        guide: ["Définissez les informations de l'API", "Ajoutez les endpoints et méthodes", "Configurez les schémas", "Exportez la spécification"] },
      { title: "JSONPath Explorer", url: "/jsonpath", desc: "Navigation JSONPath",
        shortDesc: "Explorez et interrogez des données JSON avec des expressions JSONPath et prévisualisation des résultats.",
        features: ["Éditeur d'expressions JSONPath", "Résultats en temps réel", "Référence de syntaxe", "Exemples intégrés"],
        guide: ["Collez vos données JSON", "Saisissez une expression JSONPath", "Consultez les résultats extraits", "Utilisez la référence pour la syntaxe"] },
      { title: "Anonymizer", url: "/anonymize", desc: "Anonymisation",
        shortDesc: "Anonymisez des données sensibles (noms, emails, téléphones, adresses) dans du texte ou du JSON.",
        features: ["Détection automatique de données sensibles", "Remplacement par données fictives", "Support texte et JSON", "Règles personnalisables"],
        guide: ["Collez les données contenant des informations sensibles", "Les données sensibles sont détectées automatiquement", "Vérifiez et ajustez les remplacements", "Copiez les données anonymisées"] },
      { title: "Test Matcher", url: "/test-matcher", desc: "Comparaison test",
        shortDesc: "Comparez les résultats attendus et obtenus dans vos tests avec mise en évidence des différences.",
        features: ["Comparaison JSON/texte", "Diff visuel", "Assertions simulées", "Identification des écarts"],
        guide: ["Collez le résultat attendu et le résultat obtenu", "Les différences sont surlignées", "Identifiez les écarts", "Corrigez votre code en conséquence"] },
      { title: "GraphQL Builder", url: "/graphql-builder", desc: "Schéma GraphQL",
        shortDesc: "Construisez visuellement un schéma GraphQL avec types, queries, mutations et resolvers.",
        features: ["Éditeur de types et champs", "Queries et mutations", "Relations entre types", "Export du schéma SDL"],
        guide: ["Définissez vos types GraphQL", "Ajoutez les queries et mutations", "Configurez les relations", "Exportez le schéma SDL"] },
      { title: "Seed Data", url: "/seed-data", desc: "Données seed",
        shortDesc: "Générez des scripts de seed pour votre base de données avec des données réalistes et cohérentes.",
        features: ["Scripts SQL/JS de seed", "Données réalistes", "Relations entre tables", "Volume configurable"],
        guide: ["Définissez la structure de vos tables", "Configurez le nombre de lignes par table", "Les données sont générées avec cohérence", "Copiez les scripts de seed"] },
      { title: "Prisma Builder", url: "/prisma-builder", desc: "schema.prisma",
        shortDesc: "Construisez visuellement un fichier schema.prisma avec modèles, champs, relations et attributs.",
        features: ["Éditeur visuel de modèles", "Types et attributs Prisma", "Relations configurables", "Export schema.prisma"],
        guide: ["Ajoutez des modèles", "Définissez les champs et types", "Configurez les relations", "Copiez le schema.prisma"] },
      { title: "SQL Playground", url: "/sql-playground", desc: "SQL in-browser",
        shortDesc: "Exécutez des requêtes SQL directement dans votre navigateur avec une base de données SQLite intégrée.",
        features: ["SQLite dans le navigateur", "Exécution de requêtes", "Résultats en tableau", "Schéma persistant"],
        guide: ["Créez vos tables avec CREATE TABLE", "Insérez des données", "Exécutez vos requêtes SELECT", "Consultez les résultats dans le tableau"] },
    ],
  },
  {
    label: "Mémo",
    items: [
      { title: "Cheatsheets", url: "/cheatsheets", desc: "Mémos syntaxe",
        shortDesc: "Collection de cheatsheets pour les langages et frameworks courants : syntaxe, fonctions et patterns essentiels.",
        features: ["Cheatsheets multi-langages", "Syntaxe et fonctions clés", "Recherche rapide", "Exemples de code"],
        guide: ["Sélectionnez un langage ou framework", "Parcourez les sections", "Utilisez la recherche pour trouver rapidement", "Copiez les exemples de code"] },
      { title: "HTTP Status", url: "/http-status", desc: "Codes statut",
        shortDesc: "Référence complète des codes de statut HTTP avec descriptions, cas d'usage et exemples pour chaque code.",
        features: ["Tous les codes HTTP (1xx à 5xx)", "Descriptions détaillées", "Cas d'usage courants", "Recherche et filtres"],
        guide: ["Parcourez les codes par catégorie", "Cliquez sur un code pour les détails", "Utilisez la recherche pour un code spécifique", "Consultez les cas d'usage"] },
      { title: "Glossaire", url: "/glossary", desc: "Termes dev",
        shortDesc: "Glossaire des termes de développement web avec définitions claires et exemples pour chaque concept.",
        features: ["Définitions de termes dev", "Classement alphabétique", "Recherche par mot-clé", "Exemples et contexte"],
        guide: ["Parcourez les termes par ordre alphabétique", "Utilisez la recherche pour un terme spécifique", "Consultez la définition et les exemples", "Apprenez de nouveaux concepts"] },
      { title: "Notes", url: "/notes", desc: "Notes personnelles",
        shortDesc: "Bloc-notes personnel persistant pour sauvegarder vos notes, snippets et idées en local dans le navigateur.",
        features: ["Notes persistantes (localStorage)", "Éditeur de texte", "Organisation par catégories", "Sauvegarde automatique"],
        guide: ["Créez une nouvelle note", "Rédigez votre contenu", "Les notes sont sauvegardées automatiquement", "Retrouvez-les à votre prochaine visite"] },
      { title: "Snippets", url: "/snippets", desc: "Bibliothèque code",
        shortDesc: "Bibliothèque de snippets de code réutilisables organisés par langage et catégorie avec copie rapide.",
        features: ["Snippets par langage", "Coloration syntaxique", "Copie en un clic", "Recherche et filtres"],
        guide: ["Parcourez les snippets par catégorie", "Utilisez la recherche pour trouver un pattern", "Cliquez pour copier le code", "Adaptez le snippet à votre projet"] },
      { title: "Raccourcis", url: "/shortcuts", desc: "Shortcuts clavier",
        shortDesc: "Référence des raccourcis clavier essentiels pour VS Code, Chrome DevTools, Terminal et autres outils dev.",
        features: ["Raccourcis VS Code", "Raccourcis Chrome DevTools", "Raccourcis Terminal / Shell", "Filtres par catégorie"],
        guide: ["Sélectionnez l'outil ou l'application", "Parcourez les raccourcis par catégorie", "Utilisez la recherche pour trouver un raccourci", "Mémorisez les plus utiles"] },
      { title: "Quick Ref", url: "/quick-reference", desc: "HTTP, ports…",
        shortDesc: "Référence rapide des informations essentielles : ports réseau, codes HTTP, MIME types et plus.",
        features: ["Ports réseau courants", "MIME types", "Codes d'erreur", "Valeurs par défaut"],
        guide: ["Consultez les sections de la référence", "Utilisez la recherche rapide", "Copiez les valeurs dont vous avez besoin", "Gardez cette page en favoris"] },
      { title: "ASCII/Unicode", url: "/ascii", desc: "Tables caractères",
        shortDesc: "Tables ASCII et Unicode complètes avec recherche par caractère, code décimal, hexadécimal et nom.",
        features: ["Table ASCII complète", "Caractères Unicode", "Recherche multi-critères", "Copie de caractères"],
        guide: ["Parcourez les tables de caractères", "Recherchez par nom, code ou caractère", "Cliquez pour copier un caractère", "Consultez les différentes représentations"] },
      { title: "Design Tokens", url: "/design-tokens", desc: "Tailwind, Bootstrap",
        shortDesc: "Référence des design tokens pour Tailwind CSS et Bootstrap : couleurs, espacements, breakpoints et plus.",
        features: ["Tokens Tailwind CSS", "Tokens Bootstrap", "Couleurs, espacements, typo", "Copie des valeurs"],
        guide: ["Sélectionnez le framework (Tailwind/Bootstrap)", "Parcourez les catégories de tokens", "Consultez les valeurs et classes", "Copiez les tokens pour votre projet"] },
      { title: "Best Practices", url: "/best-practices", desc: "Clean Code, SOLID",
        shortDesc: "Guide des bonnes pratiques de développement : principes SOLID, Clean Code, patterns et anti-patterns.",
        features: ["Principes SOLID expliqués", "Règles Clean Code", "Design patterns courants", "Anti-patterns à éviter"],
        guide: ["Parcourez les principes par catégorie", "Lisez les explications et exemples", "Appliquez les bonnes pratiques", "Évitez les anti-patterns identifiés"] },
      { title: "Algorithmes", url: "/algorithms", desc: "Visualisation algos",
        shortDesc: "Visualisez le fonctionnement des algorithmes de tri, recherche et structures de données avec animations pas-à-pas.",
        features: ["Algorithmes de tri (bubble, quick, merge…)", "Recherche binaire", "Arbres binaires (BST)", "Graphes et parcours", "Animation pas-à-pas"],
        guide: ["Sélectionnez un algorithme", "Configurez les données d'entrée", "Lancez l'animation pas-à-pas", "Observez et comprenez le fonctionnement"] },
      { title: "Interview", url: "/interview", desc: "Questions entretien",
        shortDesc: "Préparez vos entretiens techniques avec des questions courantes classées par thème et niveau de difficulté.",
        features: ["Questions par thème", "Niveaux junior/mid/senior", "Réponses détaillées", "Conseils d'entretien"],
        guide: ["Choisissez un thème technique", "Filtrez par niveau de difficulté", "Lisez les questions et réponses", "Pratiquez avant l'entretien"] },
      { title: "Erreurs", url: "/errors", desc: "Référence erreurs",
        shortDesc: "Catalogue exhaustif des erreurs courantes en JS, React, TypeScript, Node.js, CSS et Git avec causes, solutions et exemples de code.",
        features: ["Erreurs JavaScript, React, TypeScript, Node.js, CSS et Git", "Explications détaillées avec cause racine", "Exemples de code problématique et solutions", "Recherche par nom, message ou tag", "Liens vers la documentation officielle"],
        guide: ["Recherchez un message d'erreur ou sélectionnez un langage/outil", "Cliquez sur une erreur pour voir les détails", "Étudiez le code problématique et la solution", "Copiez les exemples de correction dans votre projet"] },
      { title: "Regex Cheatsheet", url: "/regex-cheatsheet", desc: "Référence regex",
        shortDesc: "Référence complète de la syntaxe des expressions régulières avec exemples et patterns courants.",
        features: ["Syntaxe regex complète", "Caractères spéciaux", "Quantificateurs et groupes", "Patterns courants"],
        guide: ["Consultez les sections de syntaxe", "Testez les exemples fournis", "Copiez les patterns courants", "Combinez avec l'outil Regex Pro"] },
      { title: "CSS Selectors", url: "/css-selectors", desc: "Sélecteurs CSS",
        shortDesc: "Référence complète des sélecteurs CSS avec exemples, spécificité et support navigateur.",
        features: ["Tous les sélecteurs CSS", "Exemples visuels", "Spécificité de chaque sélecteur", "Compatibilité navigateurs"],
        guide: ["Parcourez les catégories de sélecteurs", "Consultez les exemples pour chacun", "Vérifiez la compatibilité navigateur", "Utilisez comme aide-mémoire"] },
      { title: "Git Cheatsheet", url: "/git-cheatsheet", desc: "Commandes Git",
        shortDesc: "Référence des commandes Git essentielles organisées par catégorie avec exemples d'utilisation.",
        features: ["Commandes Git essentielles", "Organisation par workflow", "Exemples d'utilisation", "Astuces avancées"],
        guide: ["Parcourez les commandes par catégorie", "Consultez les exemples", "Copiez les commandes", "Découvrez les astuces avancées"] },
      { title: "Architecture", url: "/architecture", desc: "Patterns archi",
        shortDesc: "Guide des patterns d'architecture logicielle : MVC, microservices, event-driven, CQRS et plus.",
        features: ["Patterns architecturaux", "Diagrammes explicatifs", "Avantages/inconvénients", "Cas d'usage"],
        guide: ["Sélectionnez un pattern d'architecture", "Étudiez le diagramme et l'explication", "Comprenez les avantages et limites", "Identifiez le pattern adapté à votre projet"] },
      { title: "Sécurité", url: "/security-cheatsheet", desc: "OWASP, auth, headers & checklist",
        shortDesc: "Guide complet de sécurité web : OWASP Top 10, authentification JWT/OAuth, headers HTTP, checklist interactive persistante et outils recommandés.",
        features: ["OWASP Top 10 complet (A01-A10) avec code vulnérable vs sécurisé", "Auth & JWT : stockage, refresh tokens, hashage, CSRF, OAuth PKCE, 2FA", "11 security headers classés par importance avec config Helmet", "Checklist interactive par catégorie avec sauvegarde localStorage", "Annuaire d'outils de sécurité (ZAP, Snyk, Trivy, Burp Suite...)"],
        guide: ["Explorez l'onglet OWASP pour comprendre les 10 risques principaux", "Consultez Auth & JWT pour les bonnes pratiques d'authentification", "Vérifiez vos headers HTTP dans l'onglet Headers", "Cochez les items de la checklist — la progression est sauvegardée", "Découvrez les outils de sécurité recommandés dans l'onglet Outils"] },
      { title: "Linux Commands", url: "/linux-commands", desc: "Référence Linux",
        shortDesc: "Référence interactive de 60+ commandes Linux/Unix classées en 10 catégories avec syntaxe, options, exemples et section pipes & combinaisons.",
        features: ["60+ commandes essentielles", "10 catégories (fichiers, texte, réseau, processus, disque, permissions, système, transfert, archives)", "Syntaxe détaillée avec options courantes", "Exemples pratiques copiables", "Section Pipes & Combinaisons avec 10 one-liners puissants", "Recherche et filtrage rapides"],
        guide: ["Filtrez par catégorie ou recherchez une commande", "Cliquez sur une commande pour voir les détails", "Consultez la syntaxe, les options et les exemples", "Copiez les exemples directement", "Explorez la section Pipes pour des combinaisons avancées"] },
    ],
  },
];

export const toolCategories: ToolCategory[] = raw.map(cat => ({
  label: cat.label,
  tools: cat.items.map(item => ({
    title: item.title,
    url: item.url,
    category: cat.label,
    description: item.desc,
    shortDesc: item.shortDesc,
    features: item.features,
    guide: item.guide,
  })),
}));

export const allTools: ToolEntry[] = toolCategories.flatMap(c => c.tools);
export const totalToolCount = allTools.length;

/** Find tool + its category neighbors for prev/next navigation */
export function getToolContext(url: string) {
  for (const cat of toolCategories) {
    const idx = cat.tools.findIndex(t => t.url === url);
    if (idx !== -1) {
      return {
        tool: cat.tools[idx],
        category: cat.label,
        prev: idx > 0 ? cat.tools[idx - 1] : null,
        next: idx < cat.tools.length - 1 ? cat.tools[idx + 1] : null,
      };
    }
  }
  return null;
}

/** Lookup tool name by URL */
export function getToolName(url: string): string {
  return allTools.find(t => t.url === url)?.title ?? url;
}
